### ISSUE TITLE
markdown文件中的图片存放文件夹确认

### ISSUE THREAD

**Issue by yanboishere** [Web3-Club/Web3wiki-Website#24]
确认一个文件夹，未来专门放在里面。

**Comment by JiceJin** [comment]
是要一个整个项目放图片的大文件夹，还是要每个小部分要一个文件夹

**Comment by JiceJin** [comment]
是一整个项目的图片放在一个大文件夹里好，还是一个知识条目一个图片文件夹好

**Comment by yanboishere** [comment]
> 是一整个项目的图片放在一个大文件夹里好，还是一个知识条目一个图片文件夹好

放在一个大文件夹里吧。
因为咱们条目中的图片本身不多，如果一个条目一个文件夹会增加工作量。
之后我参考了下[其他wiki](https://github.com/OI-wiki/OI-wiki/tree/master/docs/images)的设置，基本都是放一个大文件夹里。

**Comment by yanboishere** [comment]
👌
