### ISSUE TITLE
Bug：删除部分 中文网页 中 的 无需翻译 外链内容

### ISSUE THREAD

**Issue by yanboishere** [Web3-Club/Web3wiki-Website#26]
此类内容无需翻译：官方网站链接、YouTube视频【暂定】
需要翻译类型举例：科普文档类
近期会将类似内容 .md文件 从 中文网页 条目中 删除
清理完毕后，该issues关闭。

**Comment by JiceJin** [comment]
https://consensys.net/blockchain-use-cases/
这种页面需要删除吗？

**Comment by JiceJin** [comment]
> https://consensys.net/blockchain-use-cases/ 这种页面需要删除吗？
基本区块链知识->区块链技术的应用和用途

**Comment by yanboishere** [comment]
是的

**Comment by yanboishere** [comment]
像这类官网 无法翻译的 可以将其从 中文翻译文件夹 剔除

**Comment by JiceJin** [comment]
https://en.wikipedia.org/wiki/Fork_(blockchain)
区块链常识->区块链分叉,这个页面是wikipedia，可能不用翻译？

**Comment by JiceJin** [comment]
标记：区块链常识->密码学是一个wikipedia

**Comment by yanboishere** [comment]
是的
<img width="915" alt="截屏2023-02-25 上午10 20 08" src="https://user-images.githubusercontent.com/76860915/221331167-897f11e6-96c6-4224-bd64-2ea4d4e5580d.png">

**Comment by yanboishere** [comment]
不用翻译

**Comment by JiceJin** [comment]
有些链接是pdf，需要翻译吗

**Comment by JiceJin** [comment]
标记：Polygon白皮书是pdf

**Comment by JiceJin** [comment]
标记：币安智能链白皮书是pdf

**Comment by JiceJin** [comment]
好吧，白皮书都是pdf，除了以太坊白皮书，但是以太坊官网已经有中文了

**Comment by JiceJin** [comment]
我现在的标准是，官网，视频等没有实际文字内容的页面，还有已经有简体中文支持的页面，这样行吗？
pdf要不要留下来？

**Comment by yanboishere** [comment]
👌

**Comment by yanboishere** [comment]
该问题已解决 https://github.com/Web3-Club/Web3wiki-Website/pull/29
