### ISSUE TITLE
网页重构需求

### ISSUE THREAD

**Issue by yanboishere** [Web3-Club/Web3wiki-Website#49]
https://github.com/Web3-Club/Web3wiki-Website/commit/d9e106f77c4d72975cb36ede15122fd48e25a6fc 和 https://github.com/Web3-Club/Web3wiki-Website/commit/b98328a564ff3ea00ace0dc86e0bb2d0196a153a 两个提交    
需要网页重构

**Comment by JiceJin** [comment]
重构的意思是有冲突吗

**Comment by JiceJin** [comment]
我刚刚pull下来，解决冲突了

**Comment by yanboishere** [comment]
已解决👌

**Comment by yanboishere** [comment]
https://github.com/Web3-Club/Web3wiki-Website/pull/50 感谢 @JiceJin 的贡献 👍
